export default {
  phone: '19999999999',
  logo: 'https://img.guanmai.cn/station_pic/gm_logo.png??imageslim',
  fee_type: 'CNY',
  address_url: 'miaoyimiao',
  sms_signature: '喵喵分仓一',
  salemenu_id: 'S8058',
  price_start_time: '2018-11-15 12:00',
  price_end_time: '2018-11-18 12:00',
  effective_time: '2021-08-03 18:00',
  sku_data: {
    A7664: [
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7664',
        category_name_1: '禽类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294802',
        sale_ratio: 1.0,
        sku_name: '鲜鸭亦',
        sale_price: 1800,
        brand: '品牌',
        origin_area: '区域',
        origin_place: '产地',
        specification_desc: '商品规格',
        feature_desc: '商品特征',
        after_sale_desc: '售后标准',
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7664',
        category_name_1: '禽类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294803',
        sale_ratio: 1.0,
        sku_name: '鸭掌',
        sale_price: 1800,
        brand: '品牌',
        origin_area: '区域',
        origin_place: '产地',
        specification_desc: '商品规格',
        feature_desc: '商品特征',
        after_sale_desc: '售后标准',
      },
      {
        sale_unit_name: '只',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7664',
        category_name_1: '禽类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '只',
        std_unit_name_forsale: '只',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294804',
        sale_ratio: 1.0,
        sku_name: '野鸭',
        sale_price: 1800,
        brand: '品牌',
        origin_area: '区域',
        origin_place: '产地',
        specification_desc: '商品规格',
        feature_desc: '商品特征',
        after_sale_desc: '售后标准',
      },
      {
        sale_unit_name: '只',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7664',
        category_name_1: '禽类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '只',
        std_unit_name_forsale: '只',
        std_sale_price_forsale: 2600,
        sku_id: 'D15294806',
        sale_ratio: 1.0,
        sku_name: '鹧鸪',
        sale_price: 2600,
        brand: '品牌',
        origin_area: '区域',
        origin_place: '产地',
        specification_desc: '商品规格',
        feature_desc: '商品特征',
        after_sale_desc: '售后标准',
      },
      {
        sale_unit_name: '只',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7664',
        category_name_1: '禽类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '只',
        std_unit_name_forsale: '只',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294805',
        sale_ratio: 1.0,
        sku_name: '鹧鸪（汤）',
        sale_price: 1800,
        brand: '品牌',
        origin_area: '区域',
        origin_place: '产地',
        specification_desc: '商品规格',
        feature_desc: '商品特征',
        after_sale_desc: '售后标准',
      },
      {
        sale_unit_name: '只',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7664',
        category_name_1: '禽类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '只',
        std_unit_name_forsale: '只',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294807',
        sale_ratio: 1.0,
        sku_name: '鹧鸪（活）',
        sale_price: 1800,
        brand: '品牌',
        origin_area: '区域',
        origin_place: '产地',
        specification_desc: '商品规格',
        feature_desc: '商品特征',
        after_sale_desc: '售后标准',
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7664',
        category_name_1: '禽类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294808',
        sale_ratio: 1.0,
        sku_name: '石燕',
        sale_price: 1800,
        brand: '品牌',
        origin_area: '区域',
        origin_place: '产地',
        specification_desc: '商品规格',
        feature_desc: '商品特征',
        after_sale_desc: '售后标准',
      },
      {
        sale_unit_name: '只',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7664',
        category_name_1: '禽类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '只',
        std_unit_name_forsale: '只',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294805',
        sale_ratio: 1.0,
        sku_name: '鹧鸪（汤）',
        sale_price: 1800,
        brand: '品牌',
        origin_area: '区域',
        origin_place: '产地',
        specification_desc: '商品规格',
        feature_desc: '商品特征',
        after_sale_desc: '售后标准',
      },
      {
        sale_unit_name: '只',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7664',
        category_name_1: '禽类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '只',
        std_unit_name_forsale: '只',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294807',
        sale_ratio: 1.0,
        sku_name: '鹧鸪（活）',
        sale_price: 1800,
        brand: '品牌',
        origin_area: '区域',
        origin_place: '产地',
        specification_desc: '商品规格',
        feature_desc: '商品特征',
        after_sale_desc: '售后标准',
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7664',
        category_name_1: '禽类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294808',
        sale_ratio: 1.0,
        sku_name: '石燕',
        sale_price: 1800,
        brand: '品牌',
        origin_area: '区域',
        origin_place: '产地',
        specification_desc: '商品规格',
        feature_desc: '商品特征',
        after_sale_desc: '售后标准',
      },
    ],
    A7668: [
      {
        sale_unit_name: '瓶',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7668',
        category_name_1: '饮料、奶类、烟酒',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '瓶',
        std_unit_name_forsale: '瓶',
        std_sale_price_forsale: 850,
        sku_id: 'D15296309',
        sale_ratio: 12.0,
        sku_name: '温氏鲜牛奶 220g|箱',
        sale_price: 10200,
        brand: '品牌',
        origin_area: '区域',
        origin_place: '产地',
        specification_desc: '商品规格',
        feature_desc: '商品特征',
        after_sale_desc: '售后标准',
      },
      {
        sale_unit_name: '瓶',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7668',
        category_name_1: '饮料、奶类、烟酒',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '瓶',
        std_unit_name_forsale: '瓶',
        std_sale_price_forsale: 1000,
        sku_id: 'D15296310',
        sale_ratio: 1.0,
        sku_name: '温氏鲜牛奶 220g',
        sale_price: 1000,
        brand: '品牌',
        origin_area: '区域',
        origin_place: '产地',
        specification_desc: '商品规格',
        feature_desc: '商品特征',
        after_sale_desc: '售后标准',
      },
      {
        sale_unit_name: '箱',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7668',
        category_name_1: '饮料、奶类、烟酒',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '箱',
        std_unit_name_forsale: '箱',
        std_sale_price_forsale: 1800,
        sku_id: 'D15296311',
        sale_ratio: 1.0,
        sku_name: '温氏常温奶 250g',
        sale_price: 1800,
        brand: '品牌',
        origin_area: '区域',
        origin_place: '产地',
        specification_desc: '商品规格',
        feature_desc: '商品特征',
        after_sale_desc: '售后标准',
      },
      {
        sale_unit_name: '瓶',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7668',
        category_name_1: '饮料、奶类、烟酒',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '瓶',
        std_unit_name_forsale: '瓶',
        std_sale_price_forsale: 1800,
        sku_id: 'D15296312',
        sale_ratio: 1.0,
        sku_name: '温氏鲜牛奶 946ml',
        sale_price: 1800,
      },
      {
        sale_unit_name: '瓶',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7668',
        category_name_1: '饮料、奶类、烟酒',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '瓶',
        std_unit_name_forsale: '瓶',
        std_sale_price_forsale: 1800,
        sku_id: 'D15296313',
        sale_ratio: 1.0,
        sku_name: '温氏高钙甜牛奶 195g',
        sale_price: 1800,
      },
      {
        sale_unit_name: '瓶',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7668',
        category_name_1: '饮料、奶类、烟酒',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '瓶',
        std_unit_name_forsale: '瓶',
        std_sale_price_forsale: 1800,
        sku_id: 'D15296314',
        sale_ratio: 1.0,
        sku_name: '橙汁',
        sale_price: 1800,
      },
      {
        sale_unit_name: '箱',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7668',
        category_name_1: '饮料、奶类、烟酒',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '箱',
        std_unit_name_forsale: '箱',
        std_sale_price_forsale: 1800,
        sku_id: 'D15296315',
        sale_ratio: 1.0,
        sku_name: '怡宝矿泉水',
        sale_price: 1800,
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7668',
        category_name_1: '饮料、奶类、烟酒',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15296316',
        sale_ratio: 1.0,
        sku_name: '冰粒',
        sale_price: 1800,
      },
    ],
    A7661: [
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294382',
        sale_ratio: 1.0,
        sku_name: '鲜羊腿',
        sale_price: 1800,
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1767,
        sku_id: 'D15294383',
        sale_ratio: 3.0,
        sku_name: '板筋',
        sale_price: 5301,
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 6,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1500.0,
        sku_id: 'D15296482',
        sale_ratio: 1.0,
        sku_name: '迟底肉',
        sale_price: 1500,
      },
      {
        sale_unit_name: '袋',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 100,
        sku_id: 'D15294352',
        sale_ratio: 3.0,
        sku_name: '抽手骨2',
        sale_price: 300,
      },
      {
        sale_unit_name: '包',
        is_price_timing: false,
        sku_version: 4,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 200.0,
        sku_id: 'D15294359',
        sale_ratio: 3.0,
        sku_name: '级大风了222',
        sale_price: 600,
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294449',
        sale_ratio: 1.0,
        sku_name: '猪红（鲜）',
        sale_price: 1800,
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294450',
        sale_ratio: 1.0,
        sku_name: '猪脚',
        sale_price: 1800,
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294451',
        sale_ratio: 1.0,
        sku_name: '猪脚尖',
        sale_price: 1800,
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294452',
        sale_ratio: 1.0,
        sku_name: '猪颈骨',
        sale_price: 1800,
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294453',
        sale_ratio: 1.0,
        sku_name: '猪颈肉',
        sale_price: 1800,
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294454',
        sale_ratio: 1.0,
        sku_name: '猪利',
        sale_price: 1800,
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294455',
        sale_ratio: 1.0,
        sku_name: '猪肉胶',
        sale_price: 1800,
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294456',
        sale_ratio: 1.0,
        sku_name: '猪手尖',
        sale_price: 1800,
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294457',
        sale_ratio: 1.0,
        sku_name: '猪头皮',
        sale_price: 1800,
        brand: '品牌',
        origin_area: '区域',
        origin_place: '产地',
        specification_desc: '商品规格',
        feature_desc: '商品特征',
        after_sale_desc: '售后标准',
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294458',
        sale_ratio: 1.0,
        sku_name: '猪尾',
        sale_price: 1800,
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294459',
        sale_ratio: 1.0,
        sku_name: '猪小肚',
        sale_price: 1800,
      },
      {
        sale_unit_name: '只',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '只',
        std_unit_name_forsale: '只',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294460',
        sale_ratio: 1.0,
        sku_name: '猪小肚(只)',
        sale_price: 1800,
        brand: '品牌',
        origin_area: '区域',
        origin_place: '产地',
        specification_desc: '商品规格',
        feature_desc: '商品特征',
        after_sale_desc: '售后标准',
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294461',
        sale_ratio: 1.0,
        sku_name: '猪小展',
        sale_price: 1800,
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294462',
        sale_ratio: 1.0,
        sku_name: '猪心',
        sale_price: 1800,
        brand: '品牌',
        origin_area: '区域',
        origin_place: '产地',
        specification_desc: '商品规格',
        feature_desc: '商品特征',
        after_sale_desc: '售后标准',
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294463',
        sale_ratio: 1.0,
        sku_name: '猪腰',
        sale_price: 1800,
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294464',
        sale_ratio: 1.0,
        sku_name: '竹肠',
        sale_price: 1800,
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294465',
        sale_ratio: 1.0,
        sku_name: '格沙肉',
        sale_price: 1800,
      },
      {
        sale_unit_name: '斤',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 1800,
        sku_id: 'D15294466',
        sale_ratio: 1.0,
        sku_name: '笋尾',
        sale_price: 1800,
      },
      {
        sale_unit_name: '件',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 590,
        sku_id: 'D15296462',
        sale_ratio: 5.0,
        sku_name: '猪排',
        sale_price: 2950,
        brand: '品牌',
        origin_area: '区域',
        origin_place: '产地',
        specification_desc: '商品规格',
        feature_desc: '商品特征',
        after_sale_desc: '售后标准',
      },
      {
        sale_unit_name: '框',
        is_price_timing: false,
        sku_version: 3,
        fee_type: 'CNY',
        category_id_1: 'A7661',
        category_name_1: '畜类',
        category_name_2: '飞鸟类',
        pinlei_name: '鸭子',
        std_unit_name: '斤',
        std_unit_name_forsale: '斤',
        std_sale_price_forsale: 880,
        sku_id: 'D15296463',
        sale_ratio: 20.0,
        sku_name: '猪排2',
        sale_price: 17600,
        brand: '品牌',
        origin_area: '区域',
        origin_place: '产地',
        specification_desc: '商品规格',
        feature_desc: '商品特征',
        after_sale_desc: '售后标准',
      },
    ],
  },
}
