export default {
  box_code: '1234',
  box_no: '1-1',
  address_name: '商户名',
  res_custom_code: 'xxxx',
  receive_time: '收货时间',
  order_id: '订单号',
  phone: '123456789012345',
  name: '喵喵总仓',
  sort_id: '01',
  details: [
    {
      spu_id: 'spu_id',
      sku_id: 'sku_id',
      sku_name: '白菜',
      quantity: 2,
      std_quantity: 1,
      std_unit_name: '斤',
      sale_unit_name: '袋',
      weighting_quantity: 1,
      std_real_quantity: 1,
      remark: '备注',
      sale_unit_weighting_quantity: 1,
    },
    {
      spu_id: 'spu_id',
      sku_id: 'sku_id',
      sku_name: '青瓜',
      quantity: 2,
      std_quantity: 1,
      std_unit_name: '斤',
      sale_unit_name: '袋',
      weighting_quantity: 1,
      std_real_quantity: 2,
      remark: '备注',
      sale_unit_weighting_quantity: 1,
    },
    {
      spu_id: 'spu_id',
      sku_id: 'sku_id',
      sku_name: '玉米',
      quantity: 2,
      std_quantity: 1,
      std_unit_name: '斤',
      sale_unit_name: '袋',
      weighting_quantity: 1,
      std_real_quantity: 3,
      remark: '备注',
      sale_unit_weighting_quantity: 1,
    },
  ],
}
