import actionTypes from '../../action.types'
import { keyMirror } from '@gm-common/tool'

export default Object.assign(
  actionTypes,
  keyMirror({
    PURCHASE_TASK_GET_SERVICE_TIME: null,

    // 采购任务列表
    PURCHASE_TASK_PAGINATION_RESET: null,
    PURCHASE_TASK_GET_FILTER_INIT_DATA: null,
    PURCHASE_TASK_HEADER_FILTER_CLEAR: null,
    PURCHASE_TASK_HEADER_FILTER_CHANGE: null,
    PURCHASE_TASK_LIST_SEARCH: null,
    PURCHASE_TASK_LIST_SEARCH_ITEM: null,
    PURCHASE_TASK_LIST_SEARCH_ITEM_CLEAR: null,
    PURCHASE_TASK_LIST_SEARCH_LOADING: null,
    PURCHASE_TASK_LIST_SEARCH_ERROR: null,
    PURCHASE_TASK_LIST_SELECT_SINGLE: null,
    PURCHASE_TASK_ORDER_SELECT_SINGLE: null,
    PURCHASE_TASK_ORDER_SELECT_ALL: null,
    PURCHASE_TASK_LIST_SELECT_ALL: null,
    PURCHASE_TASK_SUPPLIER_CAN_CHANGE_GET: null,
    PURCHASE_TASK_ORDER_SUPPLIER_EDIT_TOGGLE: null,
    PURCHASE_TASK_ORDER_SUPPLIER_CHANGE: null,
    PURCHASE_TASK_ORDER_SUPPLIER_UPDATE: null,
    PURCHASE_TASK_LIST_TASK_EXPAND_TOGGLE: null,
    PURCHASE_TASK_PRINT: null,
    PURCHASE_LIST_GET_ALL_SUPPLIER_PURCHASER: null,
    PURCHASE_TASK_SIDE_BAR_CHOOSE_ID: null,
    PURCHASE_TASK_SELECT_ROUTE: null,
    PURCHASE_TASK_LIST_PAGINATION: null,

    PURCHASE_TASK_SIDE_BAR_CHOOSE_ID_CLEAR: null,

    // 采购条目
    PURCHASE_ITEM_GET: null,
    PURCHASE_ITEM_RESET: null,
    PURCHASE_ITEM_SELECT: null,
    PURCHASE_ITEM_SELECT_ALL: null,
    PURCHASE_ITEM_SPUS_GET: null,

    // 采购记录
    PURCHASE_HISTORY_GET: null,

    // 采购员管理
    PURCHASE_SOURCER_INIT: null,
    PURCHASE_SOURCER_SEARCH: null,

    // 参考价
    PURCHASE_REFERENCE_PRICE_TYPE: null,

    // 批量修改采购任务
    PURCHASE_TASK_BATCH_MODIFY_CHANGE: null,
    PURCHASE_TASK_SETTLE_SUPPLIER_GET: null,

    // 获取子站点
    PURCHASE_TASK_GET_CHILD_STATIONS: null,

    // 获取商户标签
    PURCHASE_GET_ADDRESS_LABEL: null,
    // 获取商户列表
    PURCHASE_GET_ADDRESS_LIST: null,
  })
)
