export default {
  purchaser: [{ purchaser_id: 1, purchaser_name: 'man' }],
  settle_supplier_id: 'T4971',
  settle_supplier_name: '【总仓】蔬菜供应商',
  station_name: '总仓-李铭',
  supplier_phone_num: '12345678909',
  purchaser_phone_num: '12345678909',
  purchase_sheet_id: 'T7936-CGD-2019-09-23-00004',
  sheet_remark: '货品亮一点',
  tasks: [
    {
      sku_name: '无籽西瓜|1斤/斤',
      stock: 0.0,
      address_count: 1,
      suggest_purchase_num: 1.0,
      sale_ratio: 1.0,
      std_unit_name: '斤',
      sale_unit_name: '斤',
      price: 100.0,
      description: '漂亮的，大块的',
      goods_remark: '毛鸡',
      addresses: [
        {
          plan_purchase_amount: 3.0,
          address_id: '86939',
          sort_id: '2',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '汉虾王（南头总店）',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
        {
          plan_purchase_amount: 3.0,
          address_id: '86939',
          sort_id: '2',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '汉虾王（南头总店）',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
        {
          plan_purchase_amount: 3.0,
          address_id: '86939',
          sort_id: '2',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '汉虾王（南头总店）',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
        {
          plan_purchase_amount: 3.0,
          address_id: '86939',
          sort_id: '2',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '汉虾王（南头总店）',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
        {
          plan_purchase_amount: 1.0,
          address_id: '',
          sort_id: '233',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
      ],
    },
    {
      sku_name: '无籽西瓜|1斤/斤',
      stock: 0.0,
      address_count: 1,
      suggest_purchase_num: 1.0,
      sale_ratio: 1.0,
      std_unit_name: '斤',
      sale_unit_name: '斤',
      price: 100.0,
      description: '漂亮的，大块的',
      goods_remark: '毛鸡',
      addresses: [
        {
          plan_purchase_amount: 1.0,
          address_id: '',
          sort_id: '233',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
      ],
    },
    {
      sku_name: '无籽西瓜|1斤/斤',
      stock: 0.0,
      address_count: 1,
      suggest_purchase_num: 1.0,
      sale_ratio: 1.0,
      std_unit_name: '斤',
      sale_unit_name: '斤',
      price: 100.0,
      description: '漂亮的，大块的',
      addresses: [
        {
          plan_purchase_amount: 1.0,
          address_id: '',
          sort_id: '233',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
      ],
    },
    {
      sku_name: '无籽西瓜|1斤/斤',
      stock: 0.0,
      address_count: 1,
      suggest_purchase_num: 1.0,
      sale_ratio: 1.0,
      std_unit_name: '斤',
      sale_unit_name: '斤',
      price: 100.0,
      description: '漂亮的，大块的',
      goods_remark: '毛鸡',
      addresses: [
        {
          plan_purchase_amount: 1.0,
          address_id: '',
          sort_id: '233',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
      ],
    },
    {
      sku_name: '黑美人|1斤/斤',
      stock: -3942.0,
      address_count: 3,
      suggest_purchase_num: 0,
      description: '漂亮的，大块的',
      goods_remark: '毛鸡',
      addresses: [
        {
          plan_purchase_amount: 3.0,
          address_id: '86936',
          sort_id: '1',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '汉虾王（南头店）',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
        {
          plan_purchase_amount: 3.0,
          address_id: '86939',
          sort_id: '2',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '汉虾王（南头总店）',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
        {
          plan_purchase_amount: 3.0,
          address_id: '86939',
          sort_id: '2',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '汉虾王（南头总店）',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
        {
          plan_purchase_amount: 3.0,
          address_id: '86939',
          sort_id: '2',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '汉虾王（南头总店）',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
        {
          plan_purchase_amount: 3.0,
          address_id: '86939',
          sort_id: '2',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '汉虾王（南头总店）',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
        {
          plan_purchase_amount: 3.0,
          address_id: '86939',
          sort_id: '2',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '汉虾王（南头总店）',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
        {
          plan_purchase_amount: 3.0,
          address_id: '86939',
          sort_id: '2',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '汉虾王（南头总店）',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
        {
          plan_purchase_amount: 3.0,
          address_id: '86939',
          sort_id: '2',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '汉虾王（南头总店）',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
        {
          plan_purchase_amount: 3.0,
          address_id: '86939',
          sort_id: '2',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '汉虾王（南头总店）',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
        {
          plan_purchase_amount: 3.0,
          address_id: '86939',
          sort_id: '2',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '汉虾王（南头总店）',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
        {
          plan_purchase_amount: 3.0,
          address_id: '86939',
          sort_id: '2',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '汉虾王（南头总店）',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
        {
          plan_purchase_amount: 3.0,
          address_id: '77838',
          sort_id: '2',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '海底捞(南山店)',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
      ],
      sale_ratio: 1.0,
      std_unit_name: '斤',
      sale_unit_name: '斤',
      price: 0,
    },
    {
      sku_name: '重石馊粉|1斤/斤',
      stock: 20.0,
      address_count: 1,
      suggest_purchase_num: 30.0,
      description: '漂亮的，大块的',
      goods_remark: '毛鸡',
      addresses: [
        {
          plan_purchase_amount: 50.0,
          address_id: '77838',
          sort_id: '1',
          sale_ratio: 1.0,
          sale_unit_name: '斤',
          res_name: '海底捞(南山店)',
          remark: '',
          receive_begin_time: '2019-04-26T16:48:14',
        },
      ],
      sale_ratio: 1.0,
      std_unit_name: '斤',
      sale_unit_name: '斤',
      price: 400.0,
    },
  ],
}
