import actionTypes from '../../../action.types'
import { keyMirror } from '@gm-common/tool'

export default Object.assign(
  actionTypes,
  keyMirror({
    DISTRIBUTE_DRIVER_FILTER_CHANGE: null,
    DISTRIBUTE_DRIVER_SELECT_DATE_TYPE: null,
    DISTRIBUTE_DRIVER_DATE_PICKED: null,
    DISTRIBUTE_DRIVER_GET_DRIVER_TASK_LIST: null,
    DISTRIBUTE_DRIVER_INITIAL_SERVICE_TIMES: null,
    DISTRIBUTE_DRIVER_SELECTED_CARRIER: null,

    DISTRIBUTE_DRIVER_GET_DRIVER_ORDER_LIST: null,
    DISTRIBUTE_DRIVER_CLEAN_DRIVER_ORDER_LIST: null,
    DISTRIBUTE_DRIVER_GET_DRIVER_ORDER_LIST_TASK: null,

    DISTRIBUTE_DRIVER_GET_PRINT_TEMPLATE: null,
    DISTRIBUTE_DRIVER_SELECT_PRINT_TEMPLATE: null,

    DRIVER_ORDER_TASK_LIST_SELECTED: null,
    DRIVER_ORDER_TASK_LIST_LOADING: null,
    DRIVER_ORDER_TASK_LIST_SELECT_ALL_PAGE: null,

    DRIVER_TASK_GET_PRODUCT_DATA: null,
    DRIVER_TASK_SET_PRODUCT_PAGINATION: null,
  }),
)
