import actionTypes from '../action.types'
import { keyMirror } from '@gm-common/tool'

export default Object.assign(
  actionTypes,
  keyMirror({
    MERCHANDISE_COMMON_GET_ALL: null,
    MERCHANDISE_COMMON_GET_REFERENCE_PRICE_TYPE: null,
    MERCHANDISE_COMMON_ADD_CATE1: null,
    MERCHANDISE_COMMON_UPDATE_CATE1: null,
    MERCHANDISE_COMMON_DELETE_CATE1: null,
    MERCHANDISE_COMMON_ADD_CATE2: null,
    MERCHANDISE_COMMON_UPDATE_CATE2: null,
    MERCHANDISE_COMMON_DELETE_CATE2: null,
    MERCHANDISE_COMMON_ADD_PINLEI: null,
    MERCHANDISE_COMMON_UPDATE_PINLEI: null,
    MERCHANDISE_COMMON_DELETE_PINLEI: null,

    MERCHANDISE_SKU_COMMON_LOADING: null,

    MERCHANDISE_SKU_COMMON_SUPPLY_SKU_CREATE: null,
    MERCHANDISE_MODIFY_IMPORT_DATA: null,
  })
)
