import actionTypes from '../action.types'
import { keyMirror } from '@gm-common/tool'

export default Object.assign(
  actionTypes,
  keyMirror({
    MERCHANDISE_LIST_SPU_DETAIL: null,
    MERCHANDISE_SPU_CATEGORY: null,
    MERCHANDISE_LIST_SPU_LIST: null,
    MERCHANDISE_LIST_SPU_DETAIL_INIT: null,
    MERCHANDISE_LIST_SPU_DETAIL_CHANGE: null,
    MERCHANDISE_LIST_SPU_UPDATE: null,
    MERCHANDISE_LIST_SPU_CREATE: null,
    MERCHANDISE_SPU_DELETE: null,
    MERCHANDISE_SPU_IMG_UPLOAD: null,
    MERCHANDISE_SKU_COMMON_SKU_LIST: null,
    MERCHANDISE_SKU_COMMON_SALE_LIST: null,
    MERCHANDISE_SKU_COMMON_SUPPLY_LIST: null,
    MERCHANDISE_SKU_COMMON_CHANGE_SKU_INFO: null,
    MERCHANDISE_SKU_COMMON_IMG_UPLOAD: null,
    MERCHANDISE_SKU_COMMON_SKU_SELECTED: null,
    MERCHANDISE_SKU_COMMON_SKU_UPDATE: null,
    MERCHANDISE_SKU_COMMON_SALE_SKU_CREATE: null,
    MERCHANDISE_SKU_COMMON_RESET_STORE: null,
    MERCHANDISE_SKU_COMMON_SKU_DELETE: null,
    MERCHANDISE_COMMON_GET_INGREDIENT_LIST: null,
    MERCHANDISE_SPU_DELETE_IMAGE: null,
    MERCHANDISE_SKU_DELETE_IMAGE: null,
    MERCHANDISE_SPU_SYNC_IMG_TO_SKU: null,
    MERCHANDISE_SKU_CHANGE_CLEAN_FOOD_INFO: null,
  })
)
