module.exports = {
  port: 8787,
  proxy: [
    {
      context: [
        '/core',
        '/data_center',
        '/image',
        '/images',
        '/station',
        '/static',
        '/logo',
        '/salemenu',
        '/merchandise',
        '/product',
        '/partner-site',
        '/material',
        '/food_security_report',
        '/home_page',
        '/async_task',
        '/admin',
        '/supplier',
        '/area_dict',
        '/purchase_spec',
        '/task',
        '/process',
        '/gm_account',
        '/message',
        '/stock',
        '/purchase',
        '/coupon',
        '/weight',
        '/sms',
        '/fe',
        '/service_time',
        '/mp_third_party',
      ],
      target: 'https://station.guanmai.cn/',
      changeOrigin: true,
    },
  ],
}
