export default {
  pay_method: {
    pay_method: 1,
    cycle_length: null,
    begin_day: null,
    settle_day: null,
  },
  abnormal_money: 0.0,
  user_name: 'mmsh04',
  address_name: '八合里（深圳总店）',
  user_id: '92662',
  print_time: '2021-04-02T15:41:54.159',
  payment_name: '姐姐1',
  payment_telephone: '13611112222',
  total_price: 30.0,
  total_pay: 40.0,
  coupon_amount: 0.0,
  credit_limit: 100,
  settle_way: 1,
  telephone: '13300001111',
  freight: 10.0,
  detail: {
    D7639120: {
      name: '福满天调和油 20L',
      sku_std_outstock_quantity: 1.0,
      category_title_1: '粮油',
      sku_std_outstock_price: 6.0,
      address_detail: [{ quantity: 1.0, address_name: '八合里（深圳总店）' }],
      real_item_price: 6.0,
      pinlei_title: '油',
      quantity: 1.0,
      sale_unit_name: '罐',
      std_unit_name: '罐',
      sku_std_outstock_quantity_forsale: 1.0,
      sale_ratio: 1.0,
      category_id_1: 'A7671',
      sku_std_outstock_price_forsale: 6.0,
      category_id_2: 'B37089',
      category_title_2: '油',
      sku_id: 'D27560598',
      sid: '111111',
      sid_name: '哈哈哈哈哈哈哈',
    },
    D7639890: {
      name: '厨邦酱油 1.63L',
      sku_std_outstock_quantity: 1.0,
      category_title_1: '调味制品',
      sku_std_outstock_price: 6.0,
      address_detail: [{ quantity: 1.0, address_name: '八合里（深圳总店）' }],
      real_item_price: 6.0,
      pinlei_title: '调味酱汁类（液态）',
      quantity: 1.0,
      sale_unit_name: '支',
      std_unit_name: '支',
      sku_std_outstock_quantity_forsale: 1.0,
      sale_ratio: 1.0,
      category_id_1: 'A7663',
      sku_std_outstock_price_forsale: 6.0,
      category_id_2: 'B37063',
      category_title_2: '调味酱汁类（液态）',
      sku_id: 'D27560597',
      sid: '111111',
      sid_name: '哈哈哈哈哈哈哈',
    },
    D7638430: {
      name: '乐福万家香 15kg',
      sku_std_outstock_quantity: 3.0,
      category_title_1: '粮油',
      sku_std_outstock_price: 6.0,
      address_detail: [
        { quantity: 1.0, address_name: '八合里（深圳总店）' },
        { quantity: 1.0, address_name: '八合里（深圳总店）' },
        { quantity: 1.0, address_name: '八合里（深圳总店）' },
      ],
      real_item_price: 18.0,
      pinlei_title: '粮',
      quantity: 3.0,
      sale_unit_name: '包',
      std_unit_name: '包',
      sku_std_outstock_quantity_forsale: 3.0,
      sale_ratio: 1.0,
      category_id_1: 'A7671',
      sku_std_outstock_price_forsale: 6.0,
      category_id_2: 'B37097',
      category_title_2: '粮',
      sku_id: 'D27560596',
      sid: '111111',
      sid_name: '哈哈哈哈哈哈哈',
    },
  },
  real_price: 30.0,
}
