export default {
  package_id: 'SPA55HDZ',
  id: 'SPA55HDZ',
  sort_status: 1,
  package_date: '2020-07-01',
  quantity: 999,
  order_id: '',
  pkIndex: 0,
  sort_count: 0,
  sku_id: 'D7214251',
  sku_name: '测试果实',
  unit_name: '盒',
  total_count: 80,
  sale_ratio: 1,
  unsort_count: 80,
  outer_id: '',
  station_name: '喵喵总仓',
  phone: '13022233843',
  desc: '',
  std_unit_name: '斤',
  spu_id: 'C1275636',
  std_unit_name_forsale: '斤',
  picker_id: 'xiaoming_xx',
  picker_name: '小明',
}
