import actionTypes from '../action.types'
import { keyMirror } from '@gm-common/tool'

export default Object.assign(
  actionTypes,
  keyMirror({
    PRODUCT_SUPPLIERS: null,
    PRODUCT_SELECTED_SUPPLIER: null,
    PRODUCT_SHARE_PRODUCT: null,
    PRODUCT_SKU_LIST: null,

    // 入库
    PRODUCT_IN_STOCK_DETAIL: null,
    PRODUCT_IN_STOCK_DETAIL_INIT: null,
    PRODUCT_IN_PRODUCT_DATE_CHANGE: null,
    PRODUCT_IN_PRO_DETAIL_ADD: null,
    PRODUCT_IN_PRO_DETAIL_DEL: null,
    PRODUCT_IN_SHARE_ADD: null,
    PRODUCT_IN_SHARE_DEL: null,
    PRODUCT_IN_DISCOUNT_ADD: null,
    PRODUCT_IN_DISCOUNT_DEL: null,
    PRODUCT_IN_PRODUCT_NAME_SELECTED: null,
    PRODUCT_IN_STOCK_BATCH_IMPORT: null,
    PRODUCT_IN_PRODUCT_LIFE_TIME_CHANGE: null,
    PRODUCT_IN_PRODUCT_PRODUCTION_TIME_CHANGE: null,
    PRODUCT_IN_PRODUCT_SHELF_CHANGE: null,
    PRODUCT_IN_DETAILS_ITEM_FIELD_CHANGE: null,
    PRODUCT_IN_ORDER_REMARK_CHANGE: null,
    PRODUCT_IN_SHELF_LIST: null,

    // 出库
    PRODUCT_OUT_STOCK_CLEAR: null,
    PRODUCT_OUT_STOCK_LIST: null,
    PRODUCT_OUT_STOCK_FILTER_CHANGE: null,
    PRODUCT_OUT_STOCK_OBJECT: null,
    PRODUCT_OUT_STOCK_ID: null,
    PRODUCT_OUT_STOCK_ADD: null,
    PRODUCT_OUT_STOCK_PRO_DETAIL_ADD: null,
    PRODUCT_OUT_STOCK_PRO_DETAIL_DEL: null,
    PRODUCT_OUT_STOCK_DATE_CHANGE: null,
    PRODUCT_OUT_STOCK_DETAIL: null,
    PRODUCT_OUT_PRODUCT_NAME_SELECTED: null,
    PRODUCT_OUT_PRODUCT_QUANTITY_CHANGE: null,
    PRODUCT_OUT_PRODUCT_BATCH_SELECTED: null,
    PRODUCT_OUT_STOCK_SUBMIT: null,
    PRODUCT_OUT_STOCK_SERVICE_TIME: null,
    PRODUCT_OUT_STOCK_ANOMALY: null,

    // 退货
    PRODUCT_REFUND_STOCK_FILTER_CHANGE: null,
    PRODUCT_REFUND_STOCK_CLEAR: null,
    PRODUCT_REFUND_LIST: null,
    PRODUCT_REFUND_DETAIL: null,
    MATERIAL_REFUND_DETAIL_PRO_CHANGE: null,
    PRODUCT_REFUND_PRODUCT_QUANTITY_CHANGE: null,
    PRODUCT_REFUND_PRODUCT_PRICE_CHANGE: null,
    PRODUCT_REFUND_PRODUCT_MONEY_CHANGE: null,
    PRODUCT_REFUND_STOCK_BATCH_IMPORT: null,
    PRODUCT_REFUND_PRODUCT_BATCH_SELECTED: null,
    PRODUCT_REFUND_PRODUCT_LIST_SELECTED_CHANGE: null,
    PRODUCT_REFUND_PRODUCT_TABLE_ALL_SELECT_CHANGE: null,
    PRODUCT_REFUND_PRODUCT_CURRENT_PAGE_SELECT_CHANGE: null,
    PRODUCT_REFUND_PRODUCT_CLEAR_TABLE_SELECT: null,
    PRODUCT_REFUND_PRODUCT_PRINT_DETAIL: null,
  })
)
