import actionTypes from '../../../action.types'
import { keyMirror } from '@gm-common/tool'

export default Object.assign(
  actionTypes,
  keyMirror({
    PRICE_RULE_TAB_CHANGE: null,
    PRICE_RULE_TAB1_FILTER_CHANGE: null,
    PRICE_RULE_TAB2_FILTER_CHANGE: null,
    PRICE_RULE_CLEAR: null,
    PRICE_RULE_EDIT_CHANGE: null,
    PRICE_RULE_EDIT_DATA_CHANGE: null,
    PRICE_RULE_EDIT_SAVE: null,

    PRICE_RULE_SEARCH_BY_RULE_LOADDING_TOGGLE: null,
    PRICE_RULE_SEARCH_BY_RULE_GOT: null,
    PRICE_RULE_SEARCH_BY_SKU_LOADDING_TOGGLE: null,
    PRICE_RULE_SEARCH_BY_SKU_GOT: null,

    PRICE_RULE_SKUVIEW_RULETYPE_CHANGE: null,

    PRICE_RULE_DETAIL_GET: null,
    PRICE_RULE_DETAIL_CLEAR: null,
    PRICE_RULE_UPLOAD: null,
    PRICE_RULE_UPLOAD_CLEAR: null,
    PRICE_RULE_UPDATE_DETAIL_LIST: null,
    PRICE_RULE_DETAIL_UPLOAD_SKU_CHANGE: null,
    PRICE_RULE_DETAIL_UPLOAD_SKU_SELECT: null,
    PRICE_RULE_DETAIL_UPLOAD_SKU_DEL: null,
    PRICE_RULE_SALEMENUS_GET: null,
    PRICE_RULE_STATIONS_GET: null,
    PRICE_RULE_SKU_SEARCH_GET: null,
    PRICE_RULE_SKU_SEARCH_LOADING: null,
    PRICE_RULE_SKU_SEARCH_ERROR: null,
    PRICE_RULE_OBJECT_SEARCH_GET: null,
    PRICE_RULE_OBJECT_SEARCH_ERROR: null,
    PRICE_RULE_OBJECT_SEARCH_LOADING: null,

    PRICE_RULE_SHEET_PRICE_CHANGE: null,
    PRICE_RULE_SHEET_RULE_AND_PRICE_CHANGE: null,
    PRICE_RULE_OBJECT_ADD: null,
    PRICE_RULE_OBJECT_DEL: null,
    PRICE_RULE_SKU_ADD: null,
    PRICE_RULE_SKU_DEL: null,

    PRICE_RULE_OBJECT_INPUT_CLEAR: null,
    PRICE_RULE_SKU_INPUT_CLEAR: null,

    PRICE_RULE_PRE_CREATE: null,

    PRICE_RULE_CREATER_SHOW: null,
    PRICE_RULE_CREATER_HIDE: null,

    PRICE_RULE_SHEET_PAGE_CHANGE: null,
    PRICE_RULE_SKU_PAGINATION_CLEAR: null,

    PRICE_RULE_SET_RULE_OBJECT_TYPE: null,
    PRICE_RULE_DETAIL_SKU_CLEAR: null,
    PRICE_RULE_DETAIL_NOT_UPDATE: null,
  })
)
