export default {
  sale_ratio: 0.5,
  name_pinyin: 'baoheye|0.5jin',
  spu_name: 'spu名称',
  sale_unit_price: 581,
  driver: { source_driver_name: null, name: '*自营司机' },
  sort_id_format: 3,
  remark: '这是备注，这是备注',
  category_id_1: 'A6153',
  std_sale_price: 1162,
  production_time: '生产日期',
  life_time: '保质期',
  order: {
    source_address_id: '分仓客户编号',
    id: 'LK1721339',
    receiver_name: '小麦',
    receiver_phone: '136136136136',
    address: '深南大道666号',
    source_address_name: '分仓客户名称',
    source_sort_id: null,
    batch_remark: '',
    station_id: 'T12071',
    address_name: '南山某商户南山某商户',
    sort_id: 3,
    address_id: 'T12483',
    station_name: '某仓',
    route_name: '路线1',
    order_remark: '订单备注',
    order_time: '1970-01-01',
    receive_begin_time: '1970-01-01',
    receive_end_time: '1970-01-02',
    res_custom_code: 'QAZ12WSX',
    sale_employee_name: 'miaomiao',
    address_label_name: 'bshop',
  },
  sorter: {
    username: 'zhangsan',
    name: '张三',
  },
  phone: '400-686-3376',
  category_id_2: 'B29921',
  out_of_stock: false,
  real_quantity: 2.0,
  quantity: 2.0,
  weighting_quantity: 1.0,
  saleunit_weighting_quantity: 5,
  is_weight: true,
  sale_unit_name: '袋',
  id: 'D3516105',
  name: '薄荷叶|0.5斤',
  has_weighted: true,
  spu_id: 'C1174415',
  driver_pinyin: '*ziying',
  std_unit_name: '斤',
  food_security_code: 'a123123123',
  order_security_code: 'PL10753370D847717743A1',
  package_id: '33333333333',
  outer_id: '888888',
  page_number: '1/1',
  desc: '商品描述',
  order_id: 'sxx',
  out_stock_quantity: 1,
  out_stock_price: 2,
  pick_up_station: '观麦',
  community_name: '观麦社区',
  distributor_name: '观麦团长',
  distributor_username: '团长账户',
  distributor_address: '深南大道888号',
  distributor_phone: '13111111111',
  real_address_id: '1001',
  real_resname: '关联分仓名称',
  proc_plan_finish_time: '2090-03-04',
  proc_plan_start_time: '2090-04-03',
  clean_food_info: {
    origin_area: '产地',
    material_description: '原料说明',
    suggest_usage: '建议使用方法',
    storage_conditions: '贮存条件',
    cutting_specification: '切配规格',
    license: '许可证',
    product_standards: '产品执行标准',
    shelf_life: 500,
    nutrition_status: 1,
    nutrition_info: [
      { name: '能量', key: 'energy', per_100g: 20, NRV: 12, unit: 'KJ' },
      { name: '蛋白质', key: 'protein', per_100g: 20, NRV: 12, unit: 'g' },
      { name: '脂肪', key: 'fat', per_100g: 20, NRV: 12, unit: 'g' },
      {
        name: '碳水化合物',
        key: 'carbohydrate',
        per_100g: 20,
        NRV: 12,
        unit: 'g',
      },
      { name: '钠', key: 'element_Na', per_100g: 20, NRV: 12, unit: 'mg' },
    ],
  },
  origin_area: '我是区域',
  origin_place: '我是产地',
  brand: '我是品牌',
  specification_desc: '我是规格描述',
  feature_desc: '我是特征描述',
  after_sale_desc: '我是售后标准',
}
