import actionTypes from '../action.types'
import { keyMirror } from '@gm-common/tool'

export default Object.assign(
  actionTypes,
  keyMirror({
    PRODUCT_INVENTORY_SKU_CATEGORIES: null,
    PRODUCT_INVENTORY_TAB_KEY: null,
    PRODUCT_INVENTORY_TAB_TO_BATCH: null,
    PRODUCT_INVENTORY_RECORD_TAB_KEY: null,
    PRODUCT_INVENTORY_BATCH_LIST: null,
    PRODUCT_INVENTORY_BATCH_SELECT: null,
    PRODUCT_INVENTORY_BATCH_MANAGEMENT_LIST: null,
    PRODUCT_INVENTORY_IN_STOCK_LIST: null,
    PRODUCT_INVENTORY_INCREASE_STOCK_LIST: null,
    PRODUCT_INVENTORY_LOSS_STOCK_LIST: null,
    PRODUCT_INVENTORY_OUT_STOCK_LIST: null,
    PRODUCT_INVENTORY_PRODUCT_MANAGEMENT_LIST: null,
    PRODUCT_INVENTORY_PRODUCT_MANAGEMENT_SUM: null,
    PRODUCT_INVENTORY_REFUND_STOCK_LIST: null,
    PRODUCT_INVENTORY_RETURN_STOCK_LIST: null,
    PRODUCT_INVENTORY_SHELF_MANAGEMENT_LIST: null,
    PRODUCT_INVENTORY_SHELF_MANAGEMENT_EXPAND: null,
    PRODUCT_INVENTORY_CHANGE_RECORD_LIST: null,
    PRODUCT_INVENTORY_SUPPLEMENT_LIST: null,
    PRODUCT_INVENTORY_SERVICE_TIME: null,
    PRODUCT_INVENTORY_BATCH_FILTER_CHANGE: null,
    PRODUCT_INVENTORY_SELECT_PRODUCT: null,
    PRODUCT_INVENTORY_SELECT_ALL_PRODUCT: null,
    PRODUCT_INVENTORY_SELECT_ALL_TYPE_PRODUCT: null,

    // 修改安全库存，但不发请求先
    PRODUCT_INVENTORY_BATCH_CACHE: null,
    PRODUCT_OUT_STOCK_FILTER_CHANGE: null,
    PRODUCT_OUT_STOCK_FILTER_RESET: null,

    PRODUCT_INVENTORY_BATCH_LIST_EXPORT: null,
  })
)
