import actionTypes from '../action.types'
import { keyMirror } from '@gm-common/tool'

export default Object.assign(
  actionTypes,
  keyMirror({
    BLOCK_LINE_ADD: null,
    BLOCK_LINE_COLUMN_ADD: null,
    BLOCK_LINE_COLUMN_DEL: null,
    BLOCK_LINE_COLUMN_SETTING: null,
    BLOCK_LINE_COLUMN_SETTING_FIELD_CHANGE: null,

    BLOCK_PRODUCT_HEADER_ADD: null,
    BLOCK_PRODUCT_HEADER_ADD_DIALOG_TOGGLE: null,
    BLOCK_PRODUCT_HEADER_SETTING: null,
    BLOCK_PRODUCT_HEADER_DEL: null,

    DIALOG_FIELD_SELECTED_CHANGE: null,
    DIALOG_FIELD_SELECTED_SAVE: null,
    FIELDGROUP_ADD_DIALOG_TOGGLE: null,
    FIELDGROUP_SETTING_DIALOG_TOGGLE: null,
    FIELDGROUP_SETTING_DIALOG_SAVE: null,

    TEMPLATE_CONFIG_LIST_FETCH: null,
    TEMPLATE_CONFIG_DETAIL_FETCH: null,
    TEMPLATE_CONFIG_DETAIL_CHANGE: null,
    TEMPLATE_CONFIG_RESET: null,

    TEMPLATE_LIST_PRINTSIZE_EDIT: null,
    TEMPLATE_LIST_PRINT_PROPERTY_CHANGE: null,
    TEMPLATE_LIST_PRINTNAME_EDIT: null,
    TEMPLATE_CONFIG_LOADING_SET: null,
  })
)
